name: Deploy R packages

on:
  push:
    branches:
        - 'dev-**'

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::GIGrvg, any::coda, any::progress, any::BayesFactor, any::MASS, any::mvnfast, any::matrixcalc, any::matrixStats, any::purrr, any::dplyr, any::RSpectra, any::Matrix, any::plyr, any::CholWishart, any::magrittr, any::future, any::furrr, any::ks, any::ggplot2, any::coda, any::ggmcmc, any::caret, any::FinCovRegularization
        needs: check
   - shell: bash
        run: |
          export VERSION=$(git describe --tags --always | sed 's/v//g')
          R CMD Rd2pdf --force --no-preview -o bspcov-manual.pdf .
          sed -i '' "s/Version: [^\"]*/Version: ${VERSION}/g" "DESCRIPTION"
          R CMD build .